### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by PAHUS** [skuuu/ot-harjoitustyo#1]
**Ladattu 14:00 ma 10.12.**

Käyttöliittymä on eritelty hyvin sovelluslogiikasta, ja erittäin hyvin jaoteltu kuvaaviin paketteihin
Koodi on erittäin hyvin jaoteltu omiin kuvaaviin luokkiinsa ja luokkien metodit ovat kuvaavia ja niiden toiminnallisuus on tarpeeksi alkeellinen.

Testit ovat hyvin toteutettuja ja jaoteltuina omiin luokkinsa, selkeillä nimillä.

Luettavuuden kannalta ehkä suurin puute on kommenttien täysi puuttuminen, mutta tämä ei ole välttämättä kovin haitallista, sillä metodien nimet ovat niin kuvaavia ja lyhyitä , sekä koodi on järkevästi jaoteltu omiin kappaleisiin toiminnallisuuden mukaan. 
Kappaleille voisi lisätä kuitenkin jotain kuvaavia kommentteja tarkemman toiminnallisuuden kuvaamiseen.

Käsittääkseni Analysis-luokassa olevien muuttujakenttien näkyvyydet voisivat olla myös privateita, eikä default näkyvyyksisiä (pakkauksen sisäinen). 

Graafinen käyttöliittymä on erittäin tyylikäs ja käytettävä! Mahdollisia muutosehdotuksia: Syötettä tehtäessä ei ole selvää, mitä euro- ja sentti -kenttiin halutaan. Kentät voisivatkin olla sijoitettu esim peräkkäin, muotoon: [euros], [cents]€. Olisi myös selkeämpää jos graafin palkit eivät muuttaisi väriä uutta kategoriaa lisättäessä, vaan aina lisättäisiin uuden värinen palkki. Lisäksi y-akselin "€" saisi olla horisontaalisesti, eikä vertikaalisesti.

**Comment by skuuu** [comment]
Hei! 
Kiitos koodikatselmoinnista. 
Mainitsemasi muutosehdotukset graafiseen käyttöliittymään olivatkin jo työn alla, mutta eivät harmi kyllä ihan ehtineet koodikatselmointiin. Koodin kommentointi olisi varmasti helpottanut katselmointia, varsinkin nyt kun javadoc ei ole vielä täysin valmis. 
Korjailin Analysis-luokan muuttujien näkyvyyden ja graafista käytöliittymää muokkaillessani törmäsin myös sattumalta pylväskaavion koodissa olevaan virheeseen, mikä sai X-akselin kategoriat tietyissä tapauksissa järjestymään epätoivotusti. Kiitos siis vinkeistä, niistä oli apua :+1:  :blush:
